
#version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: nrslearning/finadviser-backend:latest
    container_name: finadviser_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: nrslearning/finadviser-frontend:latest
    container_name: finadviser_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  # Choose only one UI at a time: chainlit or streamlit
  frontend_chainlit:
    build:
      context: .
      dockerfile: Dockerfile.frontend.chainlit
    image: nrslearning/finadviser-frontend-chainlit:latest
    container_name: finadviser_frontend_chainlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
