version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_advisor_backend
    ports:
      - "8000:8000"
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app/app

  streamlit:
    image: python:3.10-slim
    container_name: stock_advisor_streamlit
    working_dir: /app
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8501:8501"
    command: bash -c "pip install --no-cache-dir -r requirements.txt && streamlit run app/frontend_ui.py"
    depends_on:
      - backend


# version: '3.8'

# services:
#   backend:
#     build: .
#     container_name: stock_advisor_backend
#     ports:
#       - "8000:8000"
#     restart: no #always

#   streamlit:
#     image: python:3.10-slim
#     container_name: stock_advisor_streamlit
#     volumes:
#       - .:/app
#     working_dir: /app
#     command: bash -c "pip install -r requirements.txt && streamlit run app_streamlit_fastApi.py"
#     ports:
#       - "8501:8501"
#     depends_on:
#       - backend
