
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: yourusername/finadviser-backend:latest
    container_name: finadviser_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: yourusername/finadviser-frontend:latest
    container_name: finadviser_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
